version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Los_Angeles"
    # we mostly want security updates, but let's also review up to two version updates per week
    open-pull-requests-limit: 2
    # let's be conservative in our changes, at least to start
    versioning-strategy: increase-if-necessary
