#!/bin/bash

set -eo pipefail

#
# This script deploys the build artifact to Pantheon.
# On the main branch the dev environment is used.
# Otherwise a multidev environment is used.
#

# Overwrite Drupal .gitattributes now that we're deploying a build artifact.
cat > .gitattributes <<EOL
# Ignore line endings in third-party text files.
web/libraries binary
web/modules/contrib binary
vendor binary
EOL

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

if [[ "$CI_BRANCH" != "$DEFAULT_BRANCH" ]] && [[ "$CI_BRANCH" != "$QA_BRANCH" ]]
then
  # Create a new multidev environment (or push to an existing one)
  terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --pr-id=$PR_NUMBER --yes
  sleep 10

  # Wake the environment to make sure the database is reachable.
  terminus -n env:wake "$TERMINUS_SITE.$TERMINUS_ENV"

  # Run myeap-deploy on the feature environment to sync database with code
  terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- cr
  sleep 10
  terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- $DRUSH_TASK

  # Clear Drupal cache
  terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- cr

  # Clear the environment cache
  terminus -n env:clear-cache "$TERMINUS_SITE.$TERMINUS_ENV"
elif [[ "$CI_BRANCH" == "$QA_BRANCH" ]]
then
  # Create a new multidev environment (or push to an existing one)
  terminus -n build:env:create "$TERMINUS_SITE.dev" "$QA_BRANCH" --pr-id=$PR_NUMBER --yes
  sleep 10

  # Wake the environment to make sure the database is reachable.
  terminus -n env:wake "$TERMINUS_SITE.$QA_BRANCH"

  # Run myeap-deploy on the feature environment to sync database with code
  terminus -n drush "$TERMINUS_SITE.$QA_BRANCH" -- cr
  sleep 10
  terminus -n drush "$TERMINUS_SITE.$QA_BRANCH" -- $DRUSH_TASK

  # Clear Drupal cache
  terminus -n drush "$TERMINUS_SITE.$QA_BRANCH" -- cr

  # Clear the environment cache
  terminus -n env:clear-cache "$TERMINUS_SITE.$QA_BRANCH"
else
  # Push to the dev environment
  terminus -n build:env:push "$TERMINUS_SITE.dev" --yes
  sleep 10

  # Wake the environment to make sure the database is reachable.
  terminus -n env:wake "$TERMINUS_SITE.dev"

  # Run myeap-deploy on the feature environment to sync database with code
  terminus -n drush "$TERMINUS_SITE.dev" -- cr
  sleep 10
  terminus -n drush "$TERMINUS_SITE.dev" -- $DRUSH_TASK

  # Clear Drupal cache
  terminus -n drush "$TERMINUS_SITE.dev" -- cr

  # Clear the environment cache
  terminus -n env:clear-cache "$TERMINUS_SITE.dev"
fi

# Ensure secrets are set
# used for [Quicksilver Pushback](https://www.github.com/pantheon-systems/quicksilver-pushback)
# which we don't currently use so no need to expose the github token if not needed.
#terminus -n secrets:set "$TERMINUS_SITE.$TERMINUS_ENV" token "${GH_TOKEN:-$GITHUB_TOKEN}" --file='.build-secrets/tokens.json' --clear --skip-if-empty
# Delete old multidev environments associated
# with a PR that has been merged or closed.
terminus -n build:env:delete:pr "$TERMINUS_SITE" --yes
