services:
  drupal:
    image: "ghcr.io/uceap/devcontainer-drupal-example:v2.3.0"
    volumes:
      - ../..:/workspaces:cached
  mariadb:
    image: "ghcr.io/uceap/devcontainer-db-example:main"
    restart: unless-stopped
  redis:
    image: "redis:6"
    restart: unless-stopped
