services:
  drupal:
    image: "ghcr.io/uceap/devcontainer-drupal:main"
    volumes:
      - ../..:/workspaces:cached
  mariadb:
    image: "ghcr.io/uceap/devcontainer-db-example:main"
    restart: always
  redis:
    image: "redis:6"
    restart: always
