# Based on https://github.com/actions/starter-workflows/blob/main/deployments/azure-container-webapp.yml
#
# For more information, see https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-docker-to-azure-app-service

name: Build and deploy to Azure

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
            ghcr.io/${{ env.REPO }}:latest
          file: ./Dockerfile
          build-args: |
            MYSQL_HOST=${{ vars.AZURE_MYSQL_HOST }}
            MYSQL_TCP_PORT=${{ vars.AZURE_MYSQL_TCP_PORT }}
            MYSQL_USER=${{ vars.AZURE_MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.AZURE_MYSQL_PASSWORD }}
            MYSQL_DATABASE=${{ vars.AZURE_MYSQL_DATABASE }}
            REDIS_HOST=${{ vars.AZURE_REDIS_HOST }}
            REDIS_AUTH=${{ secrets.AZURE_REDIS_AUTH }}
            HASH_SALT=${{ secrets.AZURE_HASH_SALT }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
