name: Cleanup multidevs
on:
  pull_request:
    types: [closed]
defaults:
  run:
    shell: bash

jobs:
  cleanup_multidevs:
    name: Cleanup multidevs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/uceap/devcontainer-drupal:main
    steps:
      - name: Prune stale multidev environments
        env:
          TERMINUS_SITE: ${{ vars.TERMINUS_SITE }}
          TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: uceap cleanup-multidevs
