name: Deploy to TEST
on:
  workflow_dispatch:
    inputs:
      deployment_type:
        description: 'Type of deployment'
        required: true
        default: 'normal'
        type: choice
        options:
        - normal
        - hotfix
jobs:
  deploy_to_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/uceap/devcontainer-drupal:main
    env:
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      TERMINUS_SITE: ${{ vars.TERMINUS_SITE }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DRUSH_TASK: ${{ vars.DRUSH_TASK }}
    steps:
      - name: Sync content and deploy to TEST
        if: ${{ github.event.inputs.deployment_type == 'normal' }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ../private.key
          chmod 600 ../private.key
          eval `ssh-agent -s`
          ssh-add ../private.key
          uceap deploy-to-test
      - name: Deploy to TEST without sync
        if: ${{ github.event.inputs.deployment_type == 'hotfix'}}
        run: |
          echo "$SSH_PRIVATE_KEY" > ../private.key
          chmod 600 ../private.key
          eval `ssh-agent -s`
          ssh-add ../private.key
          uceap deploy-to-test --no-sync
