name: Deploy to LIVE
on: workflow_dispatch
jobs:
  deploy_to_live:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/uceap/devcontainer-drupal:main
    env:
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      TERMINUS_SITE: ${{ vars.TERMINUS_SITE }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DRUSH_TASK: ${{ vars.DRUSH_TASK }}
    steps:
      - name: Deploy to LIVE
        run: |
          echo "$SSH_PRIVATE_KEY" > ../private.key
          chmod 600 ../private.key
          eval `ssh-agent -s`
          ssh-add ../private.key
          uceap deploy-to-live
